# Shell variables
# Generated by 'wal'
wallpaper='/home/kyroh/.config/wallpapers/763931.png'

# Special
background='#0e0f18'
foreground='#efe6e0'
cursor='#efe6e0'

# Colors
color0='#0e0f18'
color1='#476E90'
color2='#967789'
color3='#55B5CB'
color4='#AA9598'
color5='#D4AB99'
color6='#C6D5D1'
color7='#efe6e0'
color8='#a7a19c'
color9='#476E90'
color10='#967789'
color11='#55B5CB'
color12='#AA9598'
color13='#D4AB99'
color14='#C6D5D1'
color15='#efe6e0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
